FROM certbot/certbot:v4.1.1
MAINTAINER Open State Foundation <developers@openstate.eu>

WORKDIR /opt/certbot
RUN pip install --upgrade pip
RUN pip install certbot-dns-transip==0.5.0

ENTRYPOINT tail -f /dev/null
