FROM certbot/certbot:v1.0.0
MAINTAINER Open State Foundation <developers@openstate.eu>

WORKDIR /opt/certbot
RUN pip install --upgrade pip
RUN pip install certbot-dns-transip==0.2.5

ENTRYPOINT tail -f /dev/null
