version: '2.0'
services:
  c-nginx-load-balancer:
    image: nginx:1.21.5-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./../log/:/var/log/nginx/
      - ./../../html/:/usr/share/nginx/html/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./dhparams.pem:/etc/ssl/private/dhparams.pem
    restart: always
    networks:
      - nginx-load-balancer
  c-certbot:
    build:
      context: .
      dockerfile: Dockerfile-certbot
    restart: always
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./../../html/:/home/projects/html
      - ./transip.ini:/opt/certbot/transip.ini
      - ./transip-rsa.key:/opt/certbot/transip-rsa.key
networks:
  nginx-load-balancer:
