FROM certbot/certbot:v1.20.0
MAINTAINER Open State Foundation <developers@openstate.eu>

WORKDIR /opt/certbot
RUN pip install --upgrade pip
RUN pip install certbot-dns-transip==0.3.0

ENTRYPOINT tail -f /dev/null
