version: '2.0'
services:
  c-nginx-load-balancer:
    image: nginx:1.31.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./../log/:/var/log/nginx/
      - ./../../html/:/usr/share/nginx/html/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./dhparams.pem:/etc/ssl/private/dhparams.pem
    restart: always
    networks:
      - nginx-load-balancer
      - nginx-load-balancer-ipv6
  c-certbot:
    build:
      context: .
      dockerfile: Dockerfile-certbot
    restart: always
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./../../html/:/home/projects/html
      - ./transip.ini:/opt/certbot/transip.ini
      - ./transip-rsa.key:/opt/certbot/transip-rsa.key
networks:
  nginx-load-balancer:
  # To get IP addresses of ipv6 clients (e.g. for logging, for geolocating) nginx-load-balancer-ipv6 can be used
  # It supports both ipv4 and ipv6
  nginx-load-balancer-ipv6:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:dead:cafe::/64
